services:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.0
    container_name: logstash-elbosque
    environment:
      - xpack.monitoring.enabled=false
    volumes:
    - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    - ./logstash.yml:/usr/share/logstash/config/logstash.yml
    - ../logs:/usr/share/logstash/logs
    ports:
      - "9600:9600"
